server:
  port: 8089
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    username: root
#    password: ISbn787100
    password: 123
    url: jdbc:mysql://localhost:3306/temperature?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.fanmi.temperature.entity

#showSql
logging:
  level:
    com:
      fanmi:
        temperature:
          mapper : debug